version: "3.1"
services:
  db:
    image: mysql:latest
    container_name: ef_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: everyflavor
  redis:
    image: redis:latest
    container_name: ef_redis
    ports:
      - "6379:6379"
