ALTER TABLE IF EXISTS batches DROP FOREIGN KEY fk_batches_owner_id;
ALTER TABLE IF EXISTS batches DROP FOREIGN KEY fk_batches_recipe_id;
ALTER TABLE IF EXISTS flavors DROP FOREIGN KEY fk_flavors_vendor_id;
ALTER TABLE IF EXISTS flavor_ratings DROP FOREIGN KEY fk_flavor_ratings_flavor_id;
ALTER TABLE IF EXISTS flavor_ratings DROP FOREIGN KEY fk_flavor_ratings_owner_id;
ALTER TABLE IF EXISTS flavor_reviews DROP FOREIGN KEY fk_flavors_reviews_rating_id;
ALTER TABLE IF EXISTS recipes DROP FOREIGN KEY fk_recipes_owner_id;
ALTER TABLE IF EXISTS recipe_collaborators DROP FOREIGN KEY fk_recipe_collaborators_recipe_id;
ALTER TABLE IF EXISTS recipe_collaborators DROP FOREIGN KEY fk_recipes_collaborators_user_id;
ALTER TABLE IF EXISTS recipe_comments DROP FOREIGN KEY fk_recipes_comments_owner_id;
ALTER TABLE IF EXISTS recipe_comments DROP FOREIGN KEY fk_recipes_comments_recipe_id;
ALTER TABLE IF EXISTS recipe_comments DROP FOREIGN KEY fk_recipes_comments_reply_to_id;
ALTER TABLE IF EXISTS recipe_flavors DROP FOREIGN KEY fk_recipes_flavors_flavor_id;
ALTER TABLE IF EXISTS recipe_ratings DROP FOREIGN KEY fk_recipe_ratings_owner_id;
ALTER TABLE IF EXISTS recipe_ratings DROP FOREIGN KEY fk_recipe_ratings_recipe_id;
ALTER TABLE IF EXISTS recipe_flavors DROP FOREIGN KEY fk_recipe_flavors_recipe_id;
ALTER TABLE IF EXISTS user_roles DROP FOREIGN KEY fk_user_roles_role_id;
ALTER TABLE IF EXISTS user_roles DROP FOREIGN KEY fk_user_roles_user_id;
ALTER TABLE IF EXISTS recipe_tags DROP FOREIGN KEY fk_recipe_tags_recipe_id;
ALTER TABLE IF EXISTS recipe_tags DROP FOREIGN KEY fk_recipe_tags_tag_id;
ALTER TABLE IF EXISTS recipe_flavor_substitutions DROP FOREIGN KEY fk_recipe_flavor_sub_flavor_id;
ALTER TABLE IF EXISTS recipe_flavor_substitutions DROP FOREIGN KEY fk_recipe_flavor_sub_rf_id;

DROP TABLE IF EXISTS `batches`;
DROP TABLE IF EXISTS `flavors`;
DROP TABLE IF EXISTS `flavor_ratings`;
DROP TABLE IF EXISTS `flavor_reviews`;
DROP TABLE IF EXISTS `recipe_collaborators`;
DROP TABLE IF EXISTS `recipe_comments`;
DROP TABLE IF EXISTS `recipe_flavors`;
DROP TABLE IF EXISTS `recipe_ratings`;
DROP TABLE IF EXISTS `recipe_tags`;
DROP TABLE IF EXISTS `recipes`;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `tags`;
DROP TABLE IF EXISTS `user_roles`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `vendors`;
