// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Regenerate using `make store_mocks`

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	squirrel "github.com/Masterminds/squirrel"
)

// InsertStmtFn is an autogenerated mock type for the InsertStmtFn type
type InsertStmtFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: builder
func (_m *InsertStmtFn) Execute(builder squirrel.InsertBuilder) squirrel.InsertBuilder {
	ret := _m.Called(builder)

	var r0 squirrel.InsertBuilder
	if rf, ok := ret.Get(0).(func(squirrel.InsertBuilder) squirrel.InsertBuilder); ok {
		r0 = rf(builder)
	} else {
		r0 = ret.Get(0).(squirrel.InsertBuilder)
	}

	return r0
}
