// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Regenerate using `make store_mocks`

package mocks

import (
	model "everyflavor/internal/storage/model"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// RecipeTagStore is an autogenerated mock type for the RecipeTagStore type
type RecipeTagStore struct {
	mock.Mock
}

// DeleteAllByRecipeID provides a mock function with given fields: _a0, _a1
func (_m *RecipeTagStore) DeleteAllByRecipeID(_a0 uint64, _a1 sqlx.Execer) (int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int64
	if rf, ok := ret.Get(0).(func(uint64, sqlx.Execer) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, sqlx.Execer) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *RecipeTagStore) Insert(_a0 *model.RecipeTag, _a1 sqlx.Execer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.RecipeTag, sqlx.Execer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: _a0
func (_m *RecipeTagStore) List(_a0 model.RecipeTagParams) ([]model.RecipeTag, error) {
	ret := _m.Called(_a0)

	var r0 []model.RecipeTag
	if rf, ok := ret.Get(0).(func(model.RecipeTagParams) []model.RecipeTag); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RecipeTag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.RecipeTagParams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Replace provides a mock function with given fields: _a0, _a1, _a2
func (_m *RecipeTagStore) Replace(_a0 uint64, _a1 []model.RecipeTag, _a2 sqlx.Execer) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []model.RecipeTag, sqlx.Execer) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
