// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Regenerate using `make store_mocks`

package mocks

import mock "github.com/stretchr/testify/mock"

// ResultFn is an autogenerated mock type for the ResultFn type
type ResultFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ResultFn) Execute(_a0 int64) {
	_m.Called(_a0)
}
