// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Regenerate using `make store_mocks`

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	squirrel "github.com/Masterminds/squirrel"
)

// SelectStmtFn is an autogenerated mock type for the SelectStmtFn type
type SelectStmtFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: builder
func (_m *SelectStmtFn) Execute(builder squirrel.SelectBuilder) squirrel.SelectBuilder {
	ret := _m.Called(builder)

	var r0 squirrel.SelectBuilder
	if rf, ok := ret.Get(0).(func(squirrel.SelectBuilder) squirrel.SelectBuilder); ok {
		r0 = rf(builder)
	} else {
		r0 = ret.Get(0).(squirrel.SelectBuilder)
	}

	return r0
}
