// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Regenerate using `make store_mocks`

package mocks

import mock "github.com/stretchr/testify/mock"

// Table is an autogenerated mock type for the Table type
type Table struct {
	mock.Mock
}

// TableName provides a mock function with given fields:
func (_m *Table) TableName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
