// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Regenerate using `make store_mocks`

package mocks

import (
	model "everyflavor/internal/storage/model"

	mock "github.com/stretchr/testify/mock"
)

// TagStore is an autogenerated mock type for the TagStore type
type TagStore struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *TagStore) List() ([]model.Tag, error) {
	ret := _m.Called()

	var r0 []model.Tag
	if rf, ok := ret.Get(0).(func() []model.Tag); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
