// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

// Regenerate using `make store_mocks`

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	squirrel "github.com/Masterminds/squirrel"
)

// UpdateStmtFn is an autogenerated mock type for the UpdateStmtFn type
type UpdateStmtFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: builder
func (_m *UpdateStmtFn) Execute(builder squirrel.UpdateBuilder) squirrel.UpdateBuilder {
	ret := _m.Called(builder)

	var r0 squirrel.UpdateBuilder
	if rf, ok := ret.Get(0).(func(squirrel.UpdateBuilder) squirrel.UpdateBuilder); ok {
		r0 = rf(builder)
	} else {
		r0 = ret.Get(0).(squirrel.UpdateBuilder)
	}

	return r0
}
